## Numpy - Numerical Python
Python library - Arrays - 2005

- Lists served the purpose of arrays
- 50x faster than traditional lists
- Very frequently used in Data Science
- Mathematical foothold - Maths

Numpy stores one continuous place in memory
- Speed Efficiency
- Memory Usage - data is store contiguously in memory, which enhances performed by efficient access.
- Mathematical operations are easy
- N-Dimensional Data hanling

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
import numpy as np #Allocating an alias for the package numpy

In [7]:
a = np.array((1,2,3,4,5,6,7)) # Here no information of second dimension

In [8]:
a.shape

(7,)

In [15]:
a = np.array([[1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7]]) # I am explicity passing information of dimesions #7 and 15 both are same

In [16]:
a.shape

(7, 1)

In [17]:
a = np.array([[1,1],
              [2,2],
              [3,3],
              [4,4],
              [5,5],
              [6,6],
              [7,7]])

In [18]:
a.shape

(7, 2)

In [19]:
a.T #Transpose

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [20]:
a.T.shape

(2, 7)

## Indexing

In [21]:
a = np.array((1,2,3,4,5,6,7)) # Here no information of second dimension
print(a[0])

1


In [22]:
a = np.array([[1],
              [2],
              [3],
              [4],
              [5],
              [6],
              [7]]) # I am explicity passing information of dimesions #7 and 15 both are same
print(a[0])

[1]


In [24]:
a = np.array([[1,2],
              [2,2],
              [3,2],
              [4,2],
              [5,2],
              [6,2],
              [7,2]])
print(a[0])

[1 2]


In [25]:
a = np.array([[1,2],
              [2,2],
              [3,2],
              [4,2],
              [5,2],
              [6,2],
              [7,2]])
print(a[0][0])

1


In [26]:
a = np.array([[[1,2],
              [2,2]],
              [[3,2],
              [4,2]],
              [[5,2],
              [6,2]]])

In [28]:
a

array([[[1, 2],
        [2, 2]],

       [[3, 2],
        [4, 2]],

       [[5, 2],
        [6, 2]]])

In [27]:
a.shape

(3, 2, 2)

In [29]:
a[0]

array([[1, 2],
       [2, 2]])

In [31]:
a[0][1]

array([2, 2])

In [32]:
a[0][0][0]

1

In [34]:
a[0,1,1], a[0][0][0]

(2, 1)

In [35]:
a = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])

In [36]:
a.shape

(4, 3)

In [37]:
a = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])

In [38]:
a.shape

(2, 2, 3)

In [39]:
a

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [40]:
a[0].T

array([[1, 2],
       [2, 3],
       [3, 4]])

In [41]:
a[0].T[2] #By default numpy arrays are queried row by row to change it I am changing to column

array([3, 4])

In [50]:
a = np.array([[1,2],[3,3],[5,6],[9,8],[7,6],[0,3]])

In [51]:
a.shape

(6, 2)

In [52]:
a = np.array([[[[1,2],[3,3],[5,6]]],[[[9,8],[7,6],[0,3]]]])

In [54]:
a

array([[[[1, 2],
         [3, 3],
         [5, 6]]],


       [[[9, 8],
         [7, 6],
         [0, 3]]]])

In [53]:
a.shape

(2, 1, 3, 2)

In [56]:
a.T

array([[[[1, 9]],

        [[3, 7]],

        [[5, 0]]],


       [[[2, 8]],

        [[3, 6]],

        [[6, 3]]]])

In [55]:
a.T.shape

(2, 3, 1, 2)

In [48]:
sh = np.array([[[1,"a"],[2,"b"],[3,"c"],[4,"d"],[5,"e"],[6,"f"]]])

In [49]:
sh

array([[['1', 'a'],
        ['2', 'b'],
        ['3', 'c'],
        ['4', 'd'],
        ['5', 'e'],
        ['6', 'f']]], dtype='<U21')

In [44]:
sh.shape

(6, 2)

In [46]:
sh = np.array([[[1,"a"],[2,"b"]],[[3,"c"],[4,"d"]],[[5,"e"],[6,"f"]]])

In [47]:
sh

array([[['1', 'a'],
        ['2', 'b']],

       [['3', 'c'],
        ['4', 'd']],

       [['5', 'e'],
        ['6', 'f']]], dtype='<U21')

In [64]:
def square(num):
  """
  Signature : Square function user-defined for square operation

  Params :
  num : Integer that is to be squared

  returns : Squared Integer

  """
  a = 10 #Local Scope of the variable a - A is not present outside the function
  print(a)
  return num * num

In [67]:
square

<function __main__.square(num)>

In [68]:
def function(sffs:int,dsds:int) -> str:
  pass

In [71]:
function?