## Numpy Array Slicing

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])

In [3]:
#Slicing syntax = Arrname[start:stop:step]
print(a[0:5])

[1 2 3 4 5]


In [4]:
print(a[:5])

[1 2 3 4 5]


In [5]:
print(a[3:])

[4 5 6 7 8]


In [7]:
print(a[2:5])

[3 4 5]


In [8]:
print(a[::2])

[1 3 5 7]


## Concept of array slicing is the same for lists as well
- [] arr [start:stop:step=1]

In [10]:
lst = [1,2,3,4,5]
lst[1:5]

[2, 3, 4, 5]

## -ve Indexing

In [11]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])

In [12]:
a[-1]

8

In [13]:
a[-1::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [14]:
a[-1:-6:-1]

array([8, 7, 6, 5, 4])

In [65]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [66]:
arr.shape

(2, 4)

In [67]:
arr[0:2]

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [2, 3]])

In [19]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

In [20]:
print(arr.dtype)

int64


`i` - Integer - Sign-Bit 2^31 2^30 -------------2^1 - 32-bit - 1 <br>
`b` - Bool <br>
`u` - Unsigned Integer <br>
`f` - float <br>
`c` - complex float <br>
`m` - time delata <br>
`M` - datetime <br>
`O` - Object <br>
`S` - strings <br>

In [21]:
import numpy as np
arr = np.array([1,2,3,4,5,6], dtype= 'S')

In [22]:
print(arr.dtype)

|S1


In [23]:
print(arr)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [29]:
import numpy as np
arr = np.array(['a',2,3,4,5,6], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [31]:
import numpy as np
arr = np.array([1,0,0,1,5,6])

new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[ True False False  True  True  True]
bool


In [32]:
a = 5
if a:
  print(True)

True


In [33]:
a = None
if a:
  print(True)

In [34]:
import numpy as np
range_vals = np.array(range(0,16,1))

In [35]:
range_vals.shape

(16,)

In [39]:
matrix = range_vals.reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
matrix = range_vals.reshape(2,4,2)
matrix

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [41]:
matrix.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## flatter(), ravel()

In [42]:
matrix

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [43]:
for i in matrix:
  print(i)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [44]:
for i in matrix:
  print(i)
  for j in i:
    print(j)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1]
[2 3]
[4 5]
[6 7]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[8 9]
[10 11]
[12 13]
[14 15]


## Creating an Identity Matrix

In [45]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
np.eye(1)

array([[1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Dot product

In [48]:
matrix = range_vals.reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
I4 = np.eye(4)

In [50]:
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
assert 5==4

AssertionError: 

In [52]:
assert 4==4

In [53]:
a = np.dot(I4,matrix)
b = np.dot(matrix,I4)

In [54]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [55]:
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [63]:
assert a == b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [58]:
assert a.shape == b.shape

In [60]:
assert (a == b).all()

In [56]:
np.alltrue(a==b)

True

In [57]:
np.allclose(a,b)

True

In [59]:
np.allclose?

## Numpy Operations

In [76]:
range(0.1,1,1,0.1) #Range will not work for floats only integers

TypeError: range expected at most 3 arguments, got 4

In [70]:
matA = np.arange(0.1,1,0.1).reshape(3,3)

In [71]:
matB = matA*3

In [72]:
matC = matB*2

In [73]:
matA

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [74]:
matB

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8],
       [2.1, 2.4, 2.7]])

In [75]:
matC

array([[0.6, 1.2, 1.8],
       [2.4, 3. , 3.6],
       [4.2, 4.8, 5.4]])

In [77]:
np.add(matA,matB)

array([[0.4, 0.8, 1.2],
       [1.6, 2. , 2.4],
       [2.8, 3.2, 3.6]])

In [78]:
np.subtract(matB,matA)

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [79]:
np.multiply(matB,matA)

array([[0.03, 0.12, 0.27],
       [0.48, 0.75, 1.08],
       [1.47, 1.92, 2.43]])

## Technicallly, the matrices cannot be divided. But if you remember the basic cocept of division of two fractions, then one fraction remains the same but the other fraction gets inverted and multiplied to the former fraction for perfroming the division

In [81]:
np.divide(matA,matB)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [83]:
arr = np.array([1,2,3,4,5,6], dtype = 'float64')

In [84]:
np.reciprocal(arr)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [85]:
mat1 = np.array([1,2,3,4,5,6]).reshape(3,2)

In [86]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
mat2 = mat1 * 3

In [90]:
mat1.shape

(3, 2)

In [91]:
mat2.shape

(3, 2)

In [92]:
np.dot(mat1.T,mat2)  #@ - short hand for dot product

array([[105, 132],
       [132, 168]])

mat1.T @ mat2 #Inner Product - (2,3)(3,2) <br>
mat2.T @ mat1 #Outer Product - (3,2) (2,3)

In [93]:
arr1 = np.array([5,10,15])
arr2 = np.array([2,5,3])

In [94]:
np.mod(arr1,arr2)

array([1, 0, 0])

In [95]:
np.remainder(arr1,arr2)

array([1, 0, 0])

In [96]:
np.sin?

In [97]:
A = [[1,2],[3,4]]

In [99]:
B = np.linalg.inv(A)

In [100]:
np.dot(A,B)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])