In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [17]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
print(a.shape)
print(a[4])
b = np.array([[1],[2],[3],[4],[5],[6],[7],[8]])
print(b.shape)
print(b[7])
c = np.array([[1,2],[2,2],[3,2],[4,2],[5,2],[6,2],[7,2],[8,2]])
print(c.shape)
print(c[0],c[0][1])
cT = c.T
print(cT.shape)

(8,)
5
(8, 1)
[8]
(8, 2)
[1 2] 2
(2, 8)


In [24]:
d = np.array([[[1,2],
               [2,2]],
              [[3,2],
               [4,2]],
              [[5,2],
               [6,2]],
              [[7,2],
               [8,2]]])
print(d.shape)
print(d)
print(d[2][1][0])
print(d[3,0,0])

(4, 2, 2)
[[[1 2]
  [2 2]]

 [[3 2]
  [4 2]]

 [[5 2]
  [6 2]]

 [[7 2]
  [8 2]]]
6
7


In [27]:
e = np.array([[[1,2],
               [3,4]],
             [[5,6],
              [7,8]]])
print(e.shape)

(2, 2, 2)


In [30]:
print(e[0])
print(e[0].shape)

[[1 2]
 [3 4]]
(2, 2)


In [31]:
print(e[0].T)
print(e[0].T.shape)

[[1 3]
 [2 4]]
(2, 2)


In [35]:
g = np.array([[
               [1,2,3,4]],
             [[5,6,7,8]]])
print(g.shape)

(2, 1, 4)


In [34]:
f = np.array([[[1,2],
               [3,4],
               [5,6]],
             [[7,8],
              [9,10],
              [11,12]]])
print(f.shape)

(2, 3, 2)


In [38]:
h = np.array([
    [
        [[1,2],
         [3,3],
         [5,6]]
    ],
    [
        [[9,8],
         [7,6],
         [0,3]]
    ]
              ])
print(h.shape)  

(2, 1, 3, 2)


In [46]:
h[0]

array([[[1, 2],
        [3, 3],
        [5, 6]]])

In [47]:
h[0,0]

array([[1, 2],
       [3, 3],
       [5, 6]])

In [50]:
h[0,0,2,1]

6

In [61]:
print(h[0])
print(h[0].shape)

[[[1 2]
  [3 3]
  [5 6]]]
(1, 3, 2)


In [63]:
h0T = h[0].T
print(h0T)
print(h0T.shape)

[[[1]
  [3]
  [5]]

 [[2]
  [3]
  [6]]]
(2, 3, 1)


In [64]:
hT = h.T
print(hT)
print(hT.shape)

[[[[1 9]]

  [[3 7]]

  [[5 0]]]


 [[[2 8]]

  [[3 6]]

  [[6 3]]]]
(2, 3, 1, 2)


In [65]:
type(h)

numpy.ndarray

## Slicing Sytax = Arrname[start:stop:step] till stop-1th index is fetch

In [75]:
print(a)
print(a[1:5])
print(a[::2])
print(a[:5])
print(a[:])
print(a[:-1])
print(a[::-1])
print(a[-1::-1])
print(a[-1:-6:-1])

[1 2 3 4 5 6 7 8]
[2 3 4 5]
[1 3 5 7]
[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7]
[8 7 6 5 4 3 2 1]
[8 7 6 5 4 3 2 1]
[8 7 6 5 4]


In [95]:
arr = np.array([[1,2,3,4],
                [1,2,3,4]])
print(arr)
print(arr.shape)
print(arr[0:2,0:4])
print(arr[:1,:4])

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]]


In [105]:
arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr1)
print(arr1.shape)
print(arr1[0:1,0:4])
print(arr1[0:1,3:4])
print(arr1[0:3,3:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[1 2 3 4]]
[[4]]
[[ 4]
 [ 8]
 [12]]


In [108]:
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [109]:
arr = np.array(['a',2,3,4,5,6], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [110]:
arr = np.array([1,0,0,1,5,6])
print(arr)
print(arr.dtype)
new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[1 0 0 1 5 6]
int32
[ True False False  True  True  True]
bool


In [111]:
range_vals = np.array(range(0,16,1))
range_vals.shape

(16,)

In [112]:
matrix = range_vals.reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
matrix1 = range_vals.reshape(2,8)
matrix1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [120]:
matrix2 = range_vals.reshape(8,2)
matrix2
matrix2.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [121]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
for i in matrix:
    print(i)
    for j in i:
        print(j)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11
[12 13 14 15]
12
13
14
15


In [126]:
np.eye(0)

array([], shape=(0, 0), dtype=float64)

In [127]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [128]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [132]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [133]:
a = np.dot(matrix,I)
b = np.dot(I,matrix)

In [134]:
assert a.shape == b.shape

In [135]:
np.alltrue(a==b)

True

In [136]:
np.allclose(a,b)

True

In [138]:
np.allclose?

## Numpy Operations

In [139]:
matA = np.arange(0.1,1,0.1).reshape(3,3)
print(matA)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [140]:
matB = matA*3
print(matB)

[[0.3 0.6 0.9]
 [1.2 1.5 1.8]
 [2.1 2.4 2.7]]


In [141]:
matB

array([[0.3, 0.6, 0.9],
       [1.2, 1.5, 1.8],
       [2.1, 2.4, 2.7]])

In [143]:
matC = matB + matA
matC

array([[0.4, 0.8, 1.2],
       [1.6, 2. , 2.4],
       [2.8, 3.2, 3.6]])

In [148]:
np.add(matB,matA)

array([[0.4, 0.8, 1.2],
       [1.6, 2. , 2.4],
       [2.8, 3.2, 3.6]])

In [144]:
matC = matB - matA
matC

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [149]:
np.subtract(matB,matA)

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [145]:
matC = matB * matA
matC

array([[0.03, 0.12, 0.27],
       [0.48, 0.75, 1.08],
       [1.47, 1.92, 2.43]])

In [150]:
np.multiply(matB,matA)

array([[0.03, 0.12, 0.27],
       [0.48, 0.75, 1.08],
       [1.47, 1.92, 2.43]])

In [146]:
matC = matB / matA
matC

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [152]:
np.divide(matB,matA)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [153]:
arr = np.array([1,2,3,4,5,6],dtype = 'float64')

In [154]:
np.reciprocal(arr)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [156]:
mat1 = np.array([1,2,3,4,5,6]).reshape(3,2)
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
mat1.shape

(3, 2)

In [159]:
mat2 = mat1 * 3
mat2

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [160]:
print(mat1.shape)
print(mat2.shape)

(3, 2)
(3, 2)


In [162]:
mat1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [163]:
mat1.T.shape

(2, 3)

In [167]:
mat1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [166]:
mat2

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [169]:
np.dot(mat1.T,mat2) #@ - short hand for dot product

array([[105, 132],
       [132, 168]])

In [ ]:
mat1.T @ mat2 #Inner product - (2,3)(3,2)
mat1 @ mat2.T #outer product - (3,2)(2,3)

In [170]:
arr1 = np.array([5,10,15])
arr2 = np.array([2,5,3])

In [171]:
np.mod(arr1,arr2)

array([1, 0, 0])

In [172]:
np.remainder(arr1,arr2)

array([1, 0, 0])

In [173]:
A = [[1,2],[3,4]]

In [177]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [178]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])

In [179]:
ainv = inv(a)

In [180]:
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [181]:
#Instead of converting to boolen using astype, can we use like below:
arr = np.array([1,0,0,1,5,6], dtype='bool')
arr

array([ True, False, False,  True,  True,  True])

## Extra things from cheat_sheet
- Creating Arrays


In [203]:
np.zeros(3)

array([0., 0., 0.])

In [185]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [190]:
np.linspace(0,100,6) # Split the 0 to 100 in 6

array([  0.,  20.,  40.,  60.,  80., 100.])

In [191]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [192]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [197]:
np.random.rand(4,5) # Array of random floats between 0-1

array([[0.90469007, 0.15665717, 0.84147507, 0.2721797 , 0.2702712 ],
       [0.6271083 , 0.85382104, 0.91110972, 0.11571242, 0.31031822],
       [0.79217807, 0.41961424, 0.38911214, 0.56846499, 0.02575212],
       [0.13436273, 0.48212822, 0.52550281, 0.98753192, 0.5359311 ]])

In [196]:
np.random.rand(6,7)*100 # Array of random float between 0-100

array([[84.13397099, 86.60666359,  3.60333624,  0.32790993, 66.73520586,
        83.24475214, 64.56868951],
       [98.98194724, 49.53166096, 41.96198973, 51.72260732, 67.92768947,
        93.59688072, 33.54420026],
       [83.40971472, 23.78727179, 21.21649587, 60.74143437, 53.70087869,
        39.01463364, 35.37441692],
       [43.51609257, 53.97800025, 45.72100007, 97.80887504, 77.46394094,
        15.79196831, 10.17994262],
       [27.12099847, 20.09405289, 85.09266269, 24.97768996, 41.30980304,
        79.15977382, 44.36239711],
       [44.8341443 , 61.66060811, 32.79773503, 21.38217029, 62.33298296,
        63.52327036, 68.52168142]])

In [198]:
np.random.randint(5,size=(2,3))

array([[4, 4, 3],
       [2, 4, 4]])

## Inspecting Properties

In [210]:
arr = np.array([(1,0,3),(4,5,0)])
arr

array([[1, 0, 3],
       [4, 5, 0]])

In [205]:
arr.size

6

In [206]:
arr.shape

(2, 3)

In [207]:
arr.dtype

dtype('int32')

In [208]:
newarr = arr.astype(bool)
newarr

array([[ True, False,  True],
       [ True,  True, False]])

In [209]:
l = arr.tolist()
l

[[1, 0, 3], [4, 5, 0]]

In [211]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    com

## Copy, Sorting and Reshaping

In [212]:
arr = np.array([(1,0,3),(4,5,0)])
arr

array([[1, 0, 3],
       [4, 5, 0]])

In [213]:
new_memory = np.copy(arr)
new_memory

array([[1, 0, 3],
       [4, 5, 0]])

In [215]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])

In [216]:
y = x.view(dtype=np.int16, type=np.matrix)
y

matrix([[513]], dtype=int16)

In [217]:
arr = np.array([(1,0,3),(4,5,0)])
arr.sort()
arr

array([[0, 1, 3],
       [0, 4, 5]])

In [219]:
arr = np.array([(1,0,3),(4,5,0)])
arr.sort(axis=0)
arr

array([[1, 0, 0],
       [4, 5, 3]])

In [220]:
arr.shape

(2, 3)

In [222]:
arr.reshape(3,2)

array([[1, 0],
       [0, 4],
       [5, 3]])

In [223]:
arr.T

array([[1, 4],
       [0, 5],
       [0, 3]])

In [232]:
append_arr = np.append(arr,(2,3,4))

In [233]:
append_arr

array([1, 0, 0, 4, 5, 3, 2, 3, 4])