In [1]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

sizes = ["small", "medium", "large"]
# reshape to 2D array
sizes = np.array(sizes).reshape(-1,1)

encoded = encoder.fit_transform(sizes) 

print(encoded)

[[2.]
 [1.]
 [0.]]


In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Sample data
data = {'Customer_Satisfaction': ['Very Unsatisfied', 'Satisfied', 'Neutral', 'Very Satisfied', 'Unsatisfied']}
df = pd.DataFrame(data)

# Define the order of categories
categories = [['Very Unsatisfied', 'Unsatisfied', 'Neutral', 'Satisfied', 'Very Satisfied']]

# Create an OrdinalEncoder instance
encoder = OrdinalEncoder(categories=categories)

# Fit and transform the data
df['Satisfaction_Encoded'] = encoder.fit_transform(df[['Customer_Satisfaction']])

print(df)


  Customer_Satisfaction  Satisfaction_Encoded
0      Very Unsatisfied                   0.0
1             Satisfied                   3.0
2               Neutral                   2.0
3        Very Satisfied                   4.0
4           Unsatisfied                   1.0


In [3]:
import numpy as np

sizes = ['small', 'medium', 'large']

# Encode colors as incremental integers 
encoded_sizes = np.arange(len(sizes))

print(encoded_sizes)

[0 1 2]


In [9]:
import numpy as np
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({'X': [-5, -3, 0, 2, 4], 'y': [-10, 5, 0, 3, -1]})



In [10]:
df

X   y
0 -5 -10
1 -3   5
2  0   0
3  2   3
4  4  -1

In [11]:
# Impute negative values with the median of the positive values
df['X'] = df['X'].mask(df['X'] < 0, df['X'][df['X'] > 0].median())

In [12]:
df['X']

0    3
1    3
2    0
3    2
4    4
Name: X, dtype: int64

In [13]:
df['y'] = df['y'].mask(df['y'] < 0, df['y'][df['y'] > 0].median())

In [14]:
df['y']

0    4
1    5
2    0
3    3
4    4
Name: y, dtype: int64

In [16]:
# Shift all values by adding a constant
shift_value = abs(df['X'].min()) + 1  # Ensure all values are positive
df['X'] += shift_value
df['y'] += shift_value

In [17]:
df['X']

0    4
1    4
2    1
3    3
4    5
Name: X, dtype: int64

In [18]:
df['y']

0    5
1    6
2    1
3    4
4    5
Name: y, dtype: int64

In [19]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=2)
df_imputed = imputer.fit_transform(df)

In [20]:
df_imputed

array([[4., 5.],
       [4., 6.],
       [1., 1.],
       [3., 4.],
       [5., 5.]])